### ISSUE TITLE
relative by default

### ISSUE THREAD

**Issue by pjvds** [ridderholt/atom-relative-linenumbers#2]
Is there a way to configure the package to show relative numbers by default? I now need to toggle after opening Atom every time.

**Comment by ridderholt** [comment]
I'm sure there is a way to do this. It's one of my things that would like to do but I just haven't had the time lately to work with this extension.

**Comment by ghost** [comment]
So I have spent a couple of hours each night since you brought this to my attention looking into this and first it wasn't hard at all to get the plugin to load at startup BUT apperently there is a bug in the current version of Atom that makes the line numbers being numbered in a different way when loading this plugin from startup so that the numbers becomes totally screwed up :) I have reported this to the Atom team and I'm hoping that they will fix it in the near future.

**Comment by pjvds** [comment]
Great, thx @robinridderholt!
